{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  {{- range $key, $value := .Values.secret.values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end}}